import { Travel, TravelStatus } from './models/travel';

export const TRAVELS: Travel[] = [
  {
    id: 1,
    title: 'Карпати',
    description: 'Похід на Говерлу, кемпінг.',
    imageUrl: 'https://koruna.ua/wp-content/themes/koruna/images/gallery/2.png',
    price: 5200,
    startDate: new Date('2024-07-15'),
    status: TravelStatus.Available,
    tags: ['Гори', 'Природа', 'Релакс'],
    location: { country: 'Україна', region: 'Карпати' },
    isHot: true,
  },
  {
    id: 2,
    title: 'Ріо-де-Жанейро',
    description: 'Місто яке захоплює подих',
    imageUrl: 'https://blog.global-guide.org/wp-content/uploads/2024/12/111-54-1024x683.jpg',
    price: 15500,
    startDate: new Date('2025-02-20'),
    status: TravelStatus.ComingSoon,
    tags: ['Екзотика', 'Свято', 'Танці'],
    location: null as any,
  },
  {
    id: 3,
    title: 'Таємниці Праги',
    description: 'Прогулянки старовинними вуличками та дегустація традиційної кухні.',
    imageUrl: 'https://uni-travel.com.ua/assets/images/europe/czech/charles-bridge-prague.jpg',
    price: 10800,
    startDate: new Date('2024-05-01'),
    status: TravelStatus.SoldOut,
    tags: ['Історія', 'Місто', 'Культура'],
    location: { country: 'Чехія', region: 'Прага' },
  },
  {
    id: 4,
    title: 'Альпійські лижі',
    description: 'Екстремальні спуски та затишні вечори біля каміна.',
    imageUrl:
      'https://www.ski.ru/kohana/upload/ckfinder_images/u112805/images/112805_1549899710.jpg',
    price: 20000,
    startDate: new Date('2024-09-10'),
    status: TravelStatus.Available,
    tags: ['Лижі', 'Гори', 'Зима'],
    location: { country: 'Австрія', region: 'Тіроль' },
  },
  {
    id: 5,
    title: 'Піски Сахари',
    description: 'Ночівля в пустелі під зоряним небом та катання на верблюдах.',
    imageUrl: 'https://gsminfo.com.ua/wp-content/uploads/2022/07/pustelya.jpg',
    price: 18900,
    startDate: new Date('2024-12-25'),
    status: TravelStatus.Available,
    tags: ['Пустеля', 'Екзотика', 'Пригоди'],
    location: { country: 'Єгипет', region: 'Сахара' },
  },
];
